version: 2

builds:
  - id: shim
    main: ./cmd/shim
    binary: shim
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}

  - id: tls-egress-shim-host
    main: ./cmd/tls-egress-shim-host
    binary: tls-egress-shim-host
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}

dockers:
  - image_templates:
      - ghcr.io/tinfoilsh/nitro-attestation-shim:latest
      - ghcr.io/tinfoilsh/nitro-attestation-shim:{{ .Tag }}
    ids:
      - shim
      - tls-egress-shim-host
