version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}

dockers:
  - image_templates:
      - ghcr.io/tinfoilanalytics/nitro-attestation-shim:latest
      - ghcr.io/tinfoilanalytics/nitro-attestation-shim:{{ .Tag }}
